#!/bin/bash
# Use HandBrakeCLI to encode multiple video files.


if [ "$#" -eq 0 ]; then
    echo "Usage: compress_vids filename1 filename2 .... (wildcards are ok)"
    exit 1
fi

for filename in "$@"
do
    echo "Processing $filename"
    HandBrakeCLI -Z "Very Fast 1080p30" -i "$filename" -o "$(date +%F) ${filename%.*}_compressed.mp4"
    mv "$filename" originals
done
