#!/usr/bin/env python3
# Use HandBrakeCLI to encode multiple video files.


import argparse
import subprocess


def main():
    """Handle main."""
    parser = argparse.ArgumentParser(
        description="Run HandbrakeCLI to compress videos",
    )

    parser.add_argument(
        "files",
        metavar="files",
        type=str,
        nargs="+",
        help="Files to compress.",
    )
    parser.add_argument(
        "-p",
        "--preset",
        dest="preset",
        type=str,
        choices=["youtube", "av1", "movie"],
        default="youtube",
        help="Preset to use",
    )

    args = parser.parse_args()

    preset = "Creator 2160p60 4K"

    if args.preset == "av1":
        preset = "Fast 2160p60 4K AV1"
    elif args.preset == "movie":
        preset = "Apple 2160p60 4K HEVC Surround"

    for fname in args.files:
        print(f"Processing {fname} using preset {preset}...")
        outfname = fname.rsplit(".")[0] + f"_{args.preset}.mp4"
        subprocess.call(["HandBrakeCLI", "-Z", preset, "-i", fname, "-o", outfname])


if __name__ == "__main__":
    main()
