#!/bin/bash
# Use ffmpeg to merge multiple videos without reencoding followed by reencoding with HandBrakeCLI.
# This script requires ffmpeg and HandBrakeCLI to be installed (via homebrew) and in the path.

if [ "$#" -eq 0 ]; then
    echo "Usage: merge_vids filename1 filename2 .... (wildcards are ok)"
    exit 1
fi

name="Merged"
TMPTXT=`mktemp -p .`
for filename in "$@"
do 
    echo "file '$filename'" >> $TMPTXT
    name="${name}_${filename%.*}"
done

ffmpeg -f concat -safe 0 -i $TMPTXT -c copy "${name}_tmp.mp4"
HandBrakeCLI -Z "Very Fast 1080p30" -i "${name}_tmp.mp4" -o "$name.mp4"
rm $TMPTXT "${name}_tmp.mp4"
echo "Merged file: $name.mp4"